name:                tinyHaskell
version:             0.1.0.0
github:              "amralmorsi/tinyHaskell"
license:             BSD-3-Clause
author:              "Amr Farid Almorsi"
maintainer:          "amrfalmorsi@gmail.com"
copyright:           "2023 Amr Farid Almorsi"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            A transpiler for a subset of Haskell written in Haskell.
category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/amralmorsi/tinyHaskell#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
 
ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  exposed-modules: 
  - TinyPrelude 
  - Lib

executables:
  tinyHaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tinyHaskell
    - containers
    - mtl
    - pretty-simple

tests:
  tinyHaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tinyHaskell
    - containers
    - mtl
    - pretty-simple
